export const SET_USER_DATA = 'SET_USER_DATA';

export const CREATE_NEW_CONTACT = 'CREATE_NEW_CONTACT';
export const CREATE_NEW_CONVERSATION = 'CREATE_NEW_CONVERSATION';
export const SEND_NEW_MESSAGE = 'SEND_NEW_MESSAGE';
